name: Jekyll build and deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@master
     - uses: EdricChan03/action-build-deploy-ghpages@v2.2.0
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         gh_pages_token: ${{ secrets.GH_PAGES_TOKEN }}
                 
   
